//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cppPLUS_2407.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CorporateMaster()
        {
            this.EntityMasters = new HashSet<EntityMaster>();
        }
    
        public int Corporate_ID { get; set; }
        public string CorporateShort { get; set; }
        public string CorporateEntityName { get; set; }
        public Nullable<int> C_Country { get; set; }
        public string C_Location { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string UserID { get; set; }
    
        public virtual CountryList CountryList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityMaster> EntityMasters { get; set; }
    }
}
