//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cppPLUS_2407.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryList()
        {
            this.CorporateMasters = new HashSet<CorporateMaster>();
            this.PersonalMasters = new HashSet<PersonalMaster>();
            this.EntityMasters = new HashSet<EntityMaster>();
        }
    
        public int CountryID { get; set; }
        public string Country { get; set; }
        public string A2C { get; set; }
        public string A3C { get; set; }
        public string Cnumeric { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateMaster> CorporateMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalMaster> PersonalMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityMaster> EntityMasters { get; set; }
    }
}
