//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cppPLUS_2407.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalMaster
    {
        public int UserID { get; set; }
        public string ASPID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserStatus { get; set; }
        public string UserBackground { get; set; }
        public int UserVerification { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ShortName { get; set; }
        public string SystemName { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PostalCode { get; set; }
        public string Street { get; set; }
        public string AddAddressFld { get; set; }
        public string City { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Linkedin { get; set; }
        public string Xing { get; set; }
        public string Hyperlink1 { get; set; }
        public byte[] ProfilePic { get; set; }
        public string UserCmntPub { get; set; }
        public string UserCmntHid { get; set; }
        public int UserID_AddMod { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int ClientID { get; set; }
    
        public virtual CountryList CountryList { get; set; }
        public virtual ClientMaster ClientMaster { get; set; }
    }
}
